def add_ppo_args(parser):
    parser.add_argument('--name', type=str, default='ppo')
    parser.add_argument('--algo_type', type=str, default='rl')
    parser.add_argument('--runner', type=str, default='episode')
    parser.add_argument('--n_threads', type=int, default=1)
    parser.add_argument('--hidden_dim', type=int, default=64)
    parser.add_argument('--gamma', type=float, default=0.99)
    parser.add_argument('--lambda_', type=float, default=0.95)
    parser.add_argument('--lr', type=float, default=0.0003)
    parser.add_argument('--lr_decay_step', type=int, default=15000)
    parser.add_argument('--lr_decay_gamma', type=int, default=0.99)
    parser.add_argument('--use_entropy', default=True, action='store_true')
    parser.add_argument('--entropy_coef', type=float, default=0.01)
    parser.add_argument('--epochs', type=int, default=4)
    parser.add_argument('--eps_clip', type=float, default=0.2)
    parser.add_argument('--normalize_rewards', type=bool, default=True)
    parser.add_argument('--normalize_advantages', type=bool, default=False)
    parser.add_argument('--use_orthogonal_init', type=bool, default=False)
    parser.add_argument('--activate_fun', type=str, default='relu')
    parser.add_argument('--use_adm_epsilon', type=bool, default=False)
    parser.add_argument('--adam_epsilon', type=float, default=1e-5)
    parser.add_argument('--use_grad_clip', type=bool, default=True)
    parser.add_argument('--grad_norm_clip', type=int, default=10)
    parser.add_argument('--save_models', type=bool, default=True)
    parser.add_argument('--save_buffers', type=bool, default=False)

    parser.add_argument('--load_models', type=bool, default=False)
    parser.add_argument('--checkpoint_path', type=str, default='')

    return parser